version: '3.7'

networks:
  service-network:
    driver: bridge

services:
  db:
    image: postgres
    restart: always
    networks:
      - service-network
    environment:
      POSTGRES_DB: game-of-thrones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    networks:
      - service-network
    links:
      - db
    ports:
      - 8080:8080

  game-of-thrones-api:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    restart: always
    networks:
      - service-network
    links:
      - db
    ports:
      - '3033:3033'
