version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    networks:
      - dbnetwork
    environment:
      POSTGRES_DB: game-of-thrones
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    networks:
      - dbnetwork
    links:
      - db
    ports:
      - 8080:8080

networks:
  dbnetwork:
