version: '3.7'

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    networks:
      - observabilitynetwork
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

networks:
  observabilitynetwork:
