definitions:
  github_com_PatrickChagastavares_game-of-thrones_internal_entities.Character:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      tv_series:
        items:
          type: string
        type: array
      updated_at:
        type: string
    type: object
  github_com_PatrickChagastavares_game-of-thrones_internal_entities.CharacterRequest:
    properties:
      id:
        type: string
      name:
        type: string
      tv_series:
        items:
          type: string
        type: array
    type: object
  github_com_PatrickChagastavares_game-of-thrones_internal_entities.House:
    properties:
      created_at:
        type: string
      current_lord:
        type: string
      foundation_year:
        type: string
      id:
        type: string
      name:
        type: string
      region:
        type: string
      updated_at:
        type: string
    type: object
  github_com_PatrickChagastavares_game-of-thrones_internal_entities.HouseRequest:
    properties:
      current_lord:
        type: string
      foundation_year:
        maxLength: 5
        minLength: 1
        type: string
      name:
        maxLength: 200
        minLength: 3
        type: string
      region:
        maxLength: 100
        minLength: 3
        type: string
    required:
    - foundation_year
    - name
    - region
    type: object
  github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr:
    properties:
      http_code:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /characters:
    get:
      consumes:
      - application/json
      description: Find characters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.Character'
            type: array
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - character
    post:
      consumes:
      - application/json
      description: Create one character
      parameters:
      - description: create new character
        in: body
        name: character
        required: true
        schema:
          $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.CharacterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - character
  /characters/:id:
    delete:
      consumes:
      - application/json
      description: Delete character
      parameters:
      - description: Character ID
        in: path
        name: id
        required: true
        type: string
      - description: create new character
        in: body
        name: character
        required: true
        schema:
          $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.CharacterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.Character'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - character
    get:
      consumes:
      - application/json
      description: find character by id
      parameters:
      - description: Character ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.Character'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - character
    put:
      consumes:
      - application/json
      description: Update character
      parameters:
      - description: Character ID
        in: path
        name: id
        required: true
        type: string
      - description: create new character
        in: body
        name: character
        required: true
        schema:
          $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.CharacterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.Character'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - character
  /houses:
    get:
      consumes:
      - application/json
      description: Find houses
      parameters:
      - description: name house
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.House'
            type: array
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - house
    post:
      consumes:
      - application/json
      description: Create one house
      parameters:
      - description: create new house
        in: body
        name: house
        required: true
        schema:
          $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HouseRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - house
  /houses/:id:
    delete:
      consumes:
      - application/json
      description: Delete house
      parameters:
      - description: House ID
        in: path
        name: id
        required: true
        type: string
      - description: create new house
        in: body
        name: house
        required: true
        schema:
          $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HouseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.House'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - house
    get:
      consumes:
      - application/json
      description: find house by id
      parameters:
      - description: House ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.House'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - house
    put:
      consumes:
      - application/json
      description: Update house
      parameters:
      - description: House ID
        in: path
        name: id
        required: true
        type: string
      - description: create new house
        in: body
        name: house
        required: true
        schema:
          $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HouseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.House'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_PatrickChagastavares_game-of-thrones_internal_entities.HttpErr'
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      tags:
      - house
swagger: "2.0"
